config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope "(:locale)", locale: /en|pt-br/ do
    devise_for :accounts, controllers: { registrations: "accounts/registrations" }

    namespace :account do
      get ":account_id/dashboard" => "urls#index", as: :dashboard
      root "urls#index"
      resources :urls, only: %i[index create edit update destroy], param: :short_url
    end

    root "urls#index"
    resources :urls, only: %i[index create]
  end
  get "/:short_url", to: "urls#redirect", as: :short

  post "/change_locale/:locale", to: "settings#change_locale", as: :change_locale
end

app/views/shared/_header.html.erb
  <header class="flex flex-col md:flex-row justify-between items-center px-6 py-4 bg-white shadow-md">
    <%= link_to root_path, class: "flex items-center mb-2 md:mb-0" do %>
      <h1 class="text-xl font-bold">UrlCrew</h1>
    <% end %>
    <nav class="flex items-center space-x-4">
      <%= render "shared/select" %>
      <% if show_form_buttons? %>
        <div class="md:flex">
          <%= link_to "Log In", new_account_session_path, class: "block md:inline px-4 py-2 rounded-md bg-blue-500 text-white hover:bg-blue-600 mb-2 md:mb-0" %>
          <%= link_to t('.register'), new_account_registration_path, class: "block md:inline px-4 py-2 rounded-md border border-blue-500 text-blue-500 hover:bg-blue-100" %>
        </div>
      <% elsif show_logout_button? %>
        <%= link_to "Log Out", destroy_account_session_path, data: { "turbo-method": :delete }, class: "px-4 py-2 rounded-md bg-blue-500 text-white hover:bg-blue-600" %>
      <% end %>
    </nav>
  </header>

app/views/shared/_select.html.erb
<div class="relative inline-block text-left" data-controller="language">
  <%= select_tag "locale",
    options_for_select(
      [["English", "en"], ["Português (Brasil)", "pt-br"]], params[:locale] || I18n.locale
    ),
    {
      data: { action: "change->language#changeLocale" },
      class: "block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline"
    }
    %>
  <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
    <%= hidden_field_tag :controller, params[:controller], data: { "language-target": "controller" } %>
    <%= hidden_field_tag :action, params[:action], data: { "language-target": "action" } %>
  </div>
</div>